DELETE FROM products;

INSERT INTO products (name, serial_number, part_number, quantity, state, container, type) VALUES
('Laptop Dell XPS 13', 'DLXPS001', 'DELL-XPS-13-001', 1, 'Stored', 'Individual piece', 'PC'),
('Server Rack Components', 'SRV001', 'SRV-RACK-001', 5, 'Incoming', 'Carton', 'Rack'),
('Network Switch Cisco', 'NSW001', 'CISCO-SW-001', 1, 'Arrived', 'Individual piece', 'Server'),
('Monitor LG 27"', 'MON001', 'LG-27-001', 3, 'Outgoing', 'Carton', 'Monitor'),
('Keyboard Mechanical', 'KB001', 'MECH-KB-001', 10, 'Stored', 'Carton', 'PC'),
('Mouse Wireless', 'MS001', 'WIRE-MS-001', 5, 'Dispatched', 'Carton', 'PC'),
('Printer HP LaserJet', 'PRN001', 'HP-LJ-001', 1, 'Delivered', 'Individual piece', 'PC'),
('iPad Pro 12.9"', 'IPAD001', 'APPLE-IPAD-PRO-001', 1, 'Stored', 'Individual piece', 'PC'),
('Wireless Router TP-Link', 'ROUT001', 'TP-LINK-AC1200', 2, 'Arrived', 'Carton', 'Server'),
('External Hard Drive 2TB', 'HDD001', 'WD-ELEMENTS-2TB', 4, 'Incoming', 'Carton', 'PC'),
('USB-C Hub Multiport', 'HUB001', 'ANKER-USB-C-HUB', 6, 'Stored', 'Carton', 'PC'),
('Bluetooth Headphones', 'HEAD001', 'SONY-WH-1000XM4', 1, 'Outgoing', 'Individual piece', 'PC'),
('Webcam Logitech HD', 'CAM001', 'LOGITECH-C920', 3, 'Dispatched', 'Carton', 'PC'),
('Graphics Card NVIDIA RTX 3080', 'GPU001', 'NVIDIA-RTX3080', 1, 'Delivered', 'Individual piece', 'PC'),
('RAM DDR4 16GB Kit', 'RAM001', 'CORSAIR-VENGEANCE-16GB', 2, 'Stored', 'Individual piece', 'PC'),
('SSD Samsung 1TB', 'SSD001', 'SAMSUNG-970-EVO-1TB', 5, 'Arrived', 'Carton', 'PC'),
('Power Supply Corsair 750W', 'PSU001', 'CORSAIR-RM750', 1, 'Incoming', 'Individual piece', 'PC'),
('CPU Cooler Noctua', 'COOL001', 'NOCTUA-NH-D15', 2, 'Stored', 'Individual piece', 'PC'),
('Motherboard ASUS ROG', 'MOBO001', 'ASUS-ROG-STRIX-Z590', 1, 'Outgoing', 'Individual piece', 'PC'),
('Case Fractal Design', 'CASE001', 'FRACTAL-DESIGN-MESHIFY', 1, 'Dispatched', 'Individual piece', 'PC'),
('Projector Epson', 'PROJ001', 'EPSON-EH-TW7400', 1, 'Delivered', 'Individual piece', 'PC'),
('Smart TV Samsung 55"', 'TV001', 'SAMSUNG-QN55Q70A', 1, 'Stored', 'Individual piece', 'Monitor'),
('Soundbar Sony', 'SBAR001', 'SONY-HT-X8500', 1, 'Arrived', 'Individual piece', 'PC'),
('Gaming Console PlayStation 5', 'PS5001', 'SONY-PS5', 1, 'Incoming', 'Individual piece', 'PC'),
('VR Headset Oculus Quest 2', 'VR001', 'META-QUEST2', 2, 'Stored', 'Carton', 'PC'),
('Drone DJI Mini 2', 'DRONE001', 'DJI-MINI2', 1, 'Outgoing', 'Individual piece', 'PC'),
('Smart Watch Apple Series 8', 'WATCH001', 'APPLE-WATCH-S8', 3, 'Dispatched', 'Carton', 'PC'),
('E-Reader Kindle Paperwhite', 'KINDLE001', 'AMAZON-KINDLE-PW', 4, 'Delivered', 'Carton', 'PC'),
('Coffee Machine Nespresso', 'COFFEE001', 'NESPRESSO-VERTUO', 1, 'Stored', 'Individual piece', 'PC'),
('Air Purifier Dyson', 'PURIFIER001', 'DYSON-PURE-COOL', 1, 'Arrived', 'Individual piece', 'PC'),
('Robot Vacuum Roomba', 'ROOMBA001', 'IROBOT-ROOMBA-I7', 2, 'Incoming', 'Carton', 'PC'),
('Smart Thermostat Nest', 'THERM001', 'GOOGLE-NEST-THERMOSTAT', 3, 'Stored', 'Carton', 'PC'),
('Security Camera Ring', 'CAMRING001', 'RING-SPOTLIGHT-CAM', 5, 'Outgoing', 'Carton', 'PC');
