services:
  frontend:
    build: .
    container_name: office-frontend
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev:frontend
    env_file:
      - ./.env.local
    networks:
      - office_net

  backend:
    build: ./backend
    container_name: office-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/office
      - ALLOWED_ORIGINS=https://t-office-sigma.vercel.app
    command: npm run dev
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - office_net

  db:
    image: postgres:15
    container_name: office-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: office
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - office_net

volumes:
  postgres_data:

## docker network create office_net
networks:
  office_net:
    external: true