UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Laptop Dell XPS 13';
UPDATE products SET container = 'Carton', type = 'Rack' WHERE name = 'Server Rack Components';
UPDATE products SET container = 'Individual piece', type = 'Server' WHERE name = 'Network Switch Cisco';
UPDATE products SET container = 'Carton', type = 'Monitor' WHERE name = 'Monitor LG 27"';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'Keyboard Mechanical';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'Mouse Wireless';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Printer HP LaserJet';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'iPad Pro 12.9"';
UPDATE products SET container = 'Carton', type = 'Server' WHERE name = 'Wireless Router TP-Link';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'External Hard Drive 2TB';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'USB-C Hub Multiport';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Bluetooth Headphones';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'Webcam Logitech HD';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Graphics Card NVIDIA RTX 3080';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'RAM DDR4 16GB Kit';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'SSD Samsung 1TB';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Power Supply Corsair 750W';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'CPU Cooler Noctua';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Motherboard ASUS ROG';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Case Fractal Design';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Projector Epson';
UPDATE products SET container = 'Individual piece', type = 'Monitor' WHERE name = 'Smart TV Samsung 55"';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Soundbar Sony';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Gaming Console PlayStation 5';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'VR Headset Oculus Quest 2';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Drone DJI Mini 2';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'Smart Watch Apple Series 8';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'E-Reader Kindle Paperwhite';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Coffee Machine Nespresso';
UPDATE products SET container = 'Individual piece', type = 'PC' WHERE name = 'Air Purifier Dyson';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'Robot Vacuum Roomba';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'Smart Thermostat Nest';
UPDATE products SET container = 'Carton', type = 'PC' WHERE name = 'Security Camera Ring';
