import axios from 'axios';

// Type definitions
interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

interface ChatResponse {
  message: string;
  timestamp: Date;
}

class GroqChatService {
  private readonly GROQ_API_KEY: string;

  private readonly GROQ_BASE_URL = 'https://api.groq.com/openai/v1';

  // List of currently supported models - update as needed
  private readonly SUPPORTED_MODELS = {
    'llama-3.1-8b-instant': 'Instant model for fast responses'
  };

  // Default model to use
  private readonly DEFAULT_MODEL = 'llama-3.1-8b-instant';

  constructor() {
    // Get API key from environment variables
    // Explicitly check for NEXT_PUBLIC_GROQ_API_KEY first for browser compatibility
    this.GROQ_API_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY || this.getApiKey('GROQ_API_KEY');
    
    if (!this.GROQ_API_KEY) {
      console.warn('Groq API key not found in environment variables');
      console.warn('Please set GROQ_API_KEY or NEXT_PUBLIC_GROQ_API_KEY in your environment variables');
      console.warn('Current env keys available:', Object.keys(process.env).filter(key => key.includes('GROQ')));
    } else {
      console.log('✅ Groq API key loaded successfully');
    }
  }

  private getApiKey(keyName: string): string {
    // In browser environment, Next.js exposes NEXT_PUBLIC_ variables to the client
    if (typeof window !== 'undefined') {
      // Browser environment - check NEXT_PUBLIC_ prefix first
      const nextPublicKey = process.env[`NEXT_PUBLIC_${keyName}`];
      if (nextPublicKey) return nextPublicKey;
      
      // Also check for the key without prefix (fallback)
      const regularKey = process.env[keyName];
      if (regularKey) return regularKey;
      
      return '';
    } else {
      // Node.js environment - check regular key first, then NEXT_PUBLIC_
      const regularKey = process.env[keyName];
      if (regularKey) return regularKey;
      
      const nextPublicKey = process.env[`NEXT_PUBLIC_${keyName}`];
      if (nextPublicKey) return nextPublicKey;
      
      return '';
    }
  }

  /**
   * Send a message to Groq chat model
   * Uses the Groq API for chat completions
   */
  async sendMessage(
    message: string, 
    conversationHistory: ChatMessage[] = [], 
    model: string = this.DEFAULT_MODEL
  ): Promise<ChatResponse> {
    try {
      // Validate model is supported (warn but continue)
      if (!Object.keys(this.SUPPORTED_MODELS).includes(model)) {
        console.warn(`Model "${model}" may not be supported. Using default model instead.`);
        model = this.DEFAULT_MODEL;
      }

      // Prepare messages for the API - include conversation history
      const messages = [
        { 
          role: 'system', 
          content: 'You are a helpful assistant for the T-Office application. Provide concise, helpful responses. Be friendly and professional. Keep responses under 500 tokens.' 
        },
        ...conversationHistory.map(msg => ({
          role: msg.role,
          content: msg.content
        })),
        { role: 'user', content: message }
      ];

      const response = await axios.post(
        `${this.GROQ_BASE_URL}/chat/completions`,
        {
          model: model,
          messages: messages,
          temperature: 0.7,
          max_tokens: 500,
          top_p: 1,
          stream: false,
          stop: null,
        },
        {
          headers: {
            'Authorization': `Bearer ${this.GROQ_API_KEY}`,
            'Content-Type': 'application/json'
          },
          timeout: 30000 // 30 second timeout
        }
      );

      const botResponse = response.data.choices[0]?.message?.content;

      if (!botResponse) {
        throw new Error('No response generated by the model');
      }

      return {
        message: botResponse,
        timestamp: new Date()
      };

    } catch (error: any) {
      console.error('Error sending message to Groq:', error);
      
      // Handle specific error cases
      if (error.response) {
        const status = error.response.status;
        const errorMsg = error.response.data?.error?.message || error.response.data?.error || 'Unknown error';
        
        if (status === 429) {
          throw new Error('Rate limit exceeded. Please wait a moment before trying again.');
        } else if (status === 401) {
          throw new Error('Invalid API key. Please check your Groq API configuration.');
        } else if (status === 400) {
          // Check if it's a model deprecation error
          if (errorMsg.includes('decommissioned') || errorMsg.includes('not supported')) {
            throw new Error(`Model deprecation error: ${errorMsg}. Please use a currently supported model.`);
          }
          throw new Error(`Bad request: ${errorMsg}`);
        } else if (status >= 400 && status < 500) {
          throw new Error(`Client error (${status}): ${errorMsg}`);
        } else {
          throw new Error(`Server error (${status}): ${errorMsg}`);
        }
      } else if (error.request) {
        throw new Error('Network error: Unable to reach Groq API. Please check your connection.');
      } else {
        throw new Error(`Request failed: ${error.message}`);
      }
    }
  }

  /**
   * Get list of available models
   */
  getAvailableModels(): Record<string, string> {
    return { ...this.SUPPORTED_MODELS };
  }

  /**
   * Get the recommended model based on use case
   */
  getRecommendedModel(useCase: 'fast' | 'balanced' | 'powerful' = 'balanced'): string {
    // Only one model available
    return 'llama-3.1-8b-instant';
  }

  /**
   * Test the connection to Groq API
   */
  async testConnection(model: string = this.DEFAULT_MODEL): Promise<{ success: boolean; message: string; model: string }> {
    try {
      // Simple test with a quick request
      const response = await axios.post(
        `${this.GROQ_BASE_URL}/chat/completions`,
        {
          model: model,
          messages: [
            { role: 'system', content: 'You are a helpful assistant.' },
            { role: 'user', content: 'Hello, test connection. Respond with "OK" only.' }
          ],
          temperature: 0.1,
          max_tokens: 10,
        },
        {
          headers: {
            'Authorization': `Bearer ${this.GROQ_API_KEY}`,
            'Content-Type': 'application/json'
          },
          timeout: 10000
        }
      );
      
      return {
        success: response.status === 200,
        message: 'Connection successful',
        model: model
      };
    } catch (error: any) {
      let errorMessage = 'Connection test failed';
      
      if (error.response?.data?.error) {
        errorMessage += `: ${error.response.data.error.message || error.response.data.error}`;
      } else if (error.message) {
        errorMessage += `: ${error.message}`;
      }
      
      return {
        success: false,
        message: errorMessage,
        model: model
      };
    }
  }

  /**
   * Test multiple models to find a working one
   */
  async findWorkingModel(): Promise<string> {
    const modelsToTest = [
      'llama-3.1-8b-instant'
    ];
    
    for (const model of modelsToTest) {
      try {
        const result = await this.testConnection(model);
        if (result.success) {
          console.log(`Found working model: ${model}`);
          return model;
        }
      } catch (error) {
        continue; // Try next model
      }
    }
    
    throw new Error('No working models found. Please check your API key and network connection.');
  }
}

// Export singleton instance
export const groqChatService = new GroqChatService();
export type { ChatMessage, ChatResponse };