create table
  public.messages (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    text text null,
    constraint messages_pkey primary key (id)
  ) tablespace pg_default;
