create table
  public.attendance (
    id bigint generated by default as identity not null,
    user_id uuid not null,
    date date not null,
    sign_in_time timestamp with time zone null,
    sign_out_time timestamp with time zone null,
    constraint attendance_pkey primary key (id),
    constraint attendance_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
    constraint attendance_user_id_date_key unique (user_id, date)
  ) tablespace pg_default;
